### ISSUE TITLE
Add ability to stream messages

### ISSUE THREAD

**Issue by peburrows** [peburrows/kane#16]
Instead of requiring the calling code to call `Kane.Subscription.pull/1` repeatedly, we should add something like `Kane.Subscription.stream`

**Comment by peburrows** [comment]
Addressed as part of #22 and included in `v0.7.0-beta` (thanks @barthez!).

**Comment by popaaaandrei** [comment]
@peburrows Can we update the docs to see how to properly use `Kane.Subscription.stream` ?
Thanks!
