### ISSUE TITLE
Incorrect example in README

### ISSUE THREAD

**Issue by rubikscubemob** [peburrows/kane#23]
Using this example code in the README for subscribing we received a 404 response from GCP:

`subscription = %Kane.Subscription{topic: %Kane.Topic{name: "my-topic"}`

Changing it to:

`subscription = %Kane.Subscription{name: "my-topic"}`

seems to work better.

**Comment by peburrows** [comment]
I think the most correct syntax is actually somewhere between those two:

```elixir
%Kane.Subscription{
  name: "my-sub",
  topic: %Kane.Topic{
    name: "my-topic"
  }
}
```

I'll update the README to fix things.

**Comment by peburrows** [comment]
https://github.com/peburrows/kane/commit/b88f364bac907f56f9596565dfae0298abbc7894 should fix this.
