### ISSUE TITLE
Option to wait and not return immediately on pull

### ISSUE THREAD

**Issue by rlivsey** [peburrows/kane#9]
I notice that `Kane.Subscription.pull` has `returnImmediately` set to true.

Would you accept a PR which (optionally) sets this to false so that it will wait for new messages to enter the queue before returning? 

I assume this would also need to increase the timeout in `HTTPoison.post` (possibly to `:infinite`?).

**Comment by peburrows** [comment]
Yes, I absolutely would, as long as the default is still `true`. Thanks in advance!

**Comment by rlivsey** [comment]
👍 great, I'll work on that shortl

**Comment by peburrows** [comment]
Addressed as part of #22
